logging:
  level:
    com.daniel.scloud.demo: debug
server:
  port: 7011
ms:
  sms: ls04-ms-sms
  websiteFeign: ls04-ms-website-feign

ls04-ms-sms:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule