info:
  author: DanielDai
  name: ls03-ms-sms

spring:
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8671/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 30 #ÐÄÌø¼ì²â¼ä¸ô